//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCinema.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ProgramId { get; set; }
        public int MovieId { get; set; }
        public int SeatNo { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public int Hour { get; set; }
        public int Auditorium { get; set; }
        public string Available { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
